"""Envelope ↔ ROS2 message marshalling and SROS2 signed-node helpers.

Carries the canonical-JSON envelope wire bytes inside a `std_msgs/ByteMultiArray`
so the envelope contract from `secure_bus.py` is preserved unchanged over DDS.
The marshalling is the inverse of `envelope_to_wire` / `envelope_from_wire`:
the wire bytes are the source of truth; the ROS2 message is just a transport
container.

ADR 0011 records the dual-layer rationale (envelope signing + SROS2 signed
nodes). This module is the single integration point.

rclpy + std_msgs are optional dependencies — they're not installed in the test
environment by default. Functions that only touch wire bytes work without them
(`envelope_to_ros_msg` / `ros_msg_to_envelope` use a tiny in-process stand-in
when rclpy is absent so round-trip tests can still run); functions that
construct nodes (`make_secure_node`) raise `Sros2Unavailable`.

To enable real DDS:
    1. Install ROS2 Humble or later, source the setup script.
    2. `pip install rclpy` (system, not via uv — uv venvs don't see ROS2).
    3. `python -m specter.transport.sros2_marshal --check` confirms availability.
    4. Generate keystores: `ros2 security create_keystore <path>`.
       Per-node keys: `ros2 security create_enclave <path> /<node_name>`.
    5. Set `ROS_SECURITY_KEYSTORE=<path>`, `ROS_SECURITY_ENABLE=true`,
       `ROS_SECURITY_STRATEGY=Enforce`.
    6. Pass the keystore path to `make_secure_node`.
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from typing import Any

from ..secure_bus import Envelope, envelope_from_wire, envelope_to_wire

try:
    import rclpy  # type: ignore[import-not-found,unused-ignore]
    from rclpy.node import Node as _RclpyNode  # type: ignore[import-not-found,unused-ignore]
    from std_msgs.msg import ByteMultiArray  # type: ignore[import-not-found,unused-ignore]

    RCLPY_AVAILABLE = True
except ImportError:
    rclpy = None  # type: ignore[assignment,unused-ignore]
    _RclpyNode = None  # type: ignore[assignment,misc,unused-ignore]
    ByteMultiArray = None  # type: ignore[assignment,misc,unused-ignore]
    RCLPY_AVAILABLE = False


class Sros2Unavailable(RuntimeError):
    """Raised when an SROS2 helper is called without rclpy installed."""


@dataclass
class _StubByteMultiArray:
    """Minimal stand-in for `std_msgs/ByteMultiArray` used when rclpy is absent.

    Mirrors the only field marshalling depends on: a list of single-byte
    `bytes` values, matching the serialization rclpy's generated class uses.
    Tests can round-trip envelopes through this without ROS2 installed.
    """

    data: list[bytes] = field(default_factory=list)


def _msg_class() -> type:
    return ByteMultiArray if RCLPY_AVAILABLE else _StubByteMultiArray


def envelope_to_ros_msg(env: Envelope) -> Any:
    """Serialize an `Envelope` into a `std_msgs/ByteMultiArray` payload.

    The message's `data` field carries the same bytes `envelope_to_wire(env)`
    produces, split into one-byte entries (rclpy's expected shape for
    `ByteMultiArray.data`). Concatenating them reproduces the wire bytes
    byte-for-byte.
    """
    wire = envelope_to_wire(env)
    msg = _msg_class()()
    msg.data = [bytes([b]) for b in wire]
    return msg


def ros_msg_to_envelope(msg: Any) -> Envelope:
    """Inverse of `envelope_to_ros_msg`. Raises on malformed input via the
    underlying `envelope_from_wire`."""
    wire = b"".join(msg.data)
    return envelope_from_wire(wire)


def make_secure_node(name: str, keystore_path: str | None = None) -> Any:
    """Construct an `rclpy.Node` configured for SROS2 signed-node DDS.

    When `keystore_path` is provided, sets the standard SROS2 environment
    variables (`ROS_SECURITY_KEYSTORE`, `ROS_SECURITY_ENABLE=true`,
    `ROS_SECURITY_STRATEGY=Enforce`) before initializing rclpy so the DDS
    layer enforces signed-node authentication. The keystore must already
    contain an enclave for `/<name>` (generated by
    `ros2 security create_enclave`).

    Raises `Sros2Unavailable` when rclpy isn't installed.
    """
    if not RCLPY_AVAILABLE:
        raise Sros2Unavailable("rclpy is not installed; see module docstring")
    if keystore_path is not None:
        os.environ["ROS_SECURITY_KEYSTORE"] = keystore_path
        os.environ["ROS_SECURITY_ENABLE"] = "true"
        os.environ["ROS_SECURITY_STRATEGY"] = "Enforce"
    if not rclpy.ok():
        rclpy.init()
    return _RclpyNode(name)
